language: go

sudo: required
dist: trusty

go:
  - 1.8
  - 1.9
  - master
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

cache: apt

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/Masterminds/glide
  - glide install

script:
  - make travis
  - goveralls -service=travis-ci
